require:
  - rubocop-rails
  - rubocop-rspec

Metrics/MethodLength:
  Description: 'Avoid methods longer than 20 lines of code.'
  Max: 20

RSpec/ExampleLength:
  Max: 10

Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude: 
    - spec/**/*_spec.rb

Style/TrailingCommaInArrayLiteral:
  Enabled: false